{
   "type":"MODIFIED",
   "object":{
      "kind":"Node",
      "apiVersion":"v1",
      "metadata":{
         "name":"kind-control-plane",
         "uid":"1d44438c-a5c6-4c62-a7a4-9e83723da205",
         "resourceVersion":"27806",
         "creationTimestamp":"2023-12-06T14:21:10Z",
         "labels":{
            "beta.kubernetes.io/arch":"arm64",
            "beta.kubernetes.io/os":"linux",
            "katsoulis":"pasole",
            "kubernetes.io/arch":"arm64",
            "kubernetes.io/hostname":"kind-control-plane",
            "kubernetes.io/os":"linux",
            "node-role.kubernetes.io/control-plane":"",
            "node.kubernetes.io/exclude-from-external-load-balancers":""
         },
         "annotations":{
            "kubeadm.alpha.kubernetes.io/cri-socket":"unix:///run/containerd/containerd.sock",
            "node.alpha.kubernetes.io/ttl":"0",
            "volumes.kubernetes.io/controller-managed-attach-detach":"true"
         },
         "managedFields":[
            {
               "manager":"kubelet",
               "operation":"Update",
               "apiVersion":"v1",
               "time":"2023-12-06T14:21:10Z",
               "fieldsType":"FieldsV1",
               "fieldsV1":{
                  "f:metadata":{
                     "f:annotations":{
                        ".":{
                           
                        },
                        "f:volumes.kubernetes.io/controller-managed-attach-detach":{
                           
                        }
                     },
                     "f:labels":{
                        ".":{
                           
                        },
                        "f:beta.kubernetes.io/arch":{
                           
                        },
                        "f:beta.kubernetes.io/os":{
                           
                        },
                        "f:kubernetes.io/arch":{
                           
                        },
                        "f:kubernetes.io/hostname":{
                           
                        },
                        "f:kubernetes.io/os":{
                           
                        }
                     }
                  },
                  "f:spec":{
                     "f:providerID":{
                        
                     }
                  }
               }
            },
            {
               "manager":"kubeadm",
               "operation":"Update",
               "apiVersion":"v1",
               "time":"2023-12-06T14:21:12Z",
               "fieldsType":"FieldsV1",
               "fieldsV1":{
                  "f:metadata":{
                     "f:annotations":{
                        "f:kubeadm.alpha.kubernetes.io/cri-socket":{
                           
                        }
                     },
                     "f:labels":{
                        "f:node-role.kubernetes.io/control-plane":{
                           
                        },
                        "f:node.kubernetes.io/exclude-from-external-load-balancers":{
                           
                        }
                     }
                  }
               }
            },
            {
               "manager":"kube-controller-manager",
               "operation":"Update",
               "apiVersion":"v1",
               "time":"2023-12-06T14:21:25Z",
               "fieldsType":"FieldsV1",
               "fieldsV1":{
                  "f:metadata":{
                     "f:annotations":{
                        "f:node.alpha.kubernetes.io/ttl":{
                           
                        }
                     }
                  },
                  "f:spec":{
                     "f:podCIDR":{
                        
                     },
                     "f:podCIDRs":{
                        ".":{
                           
                        },
                        "v:\"10.244.0.0/24\"":{
                           
                        }
                     }
                  }
               }
            },
            {
               "manager":"kubectl-label",
               "operation":"Update",
               "apiVersion":"v1",
               "time":"2023-12-07T11:28:02Z",
               "fieldsType":"FieldsV1",
               "fieldsV1":{
                  "f:metadata":{
                     "f:labels":{
                        "f:katsoulis":{
                           
                        }
                     }
                  }
               }
            },
            {
               "manager":"kubelet",
               "operation":"Update",
               "apiVersion":"v1",
               "time":"2023-12-07T11:50:27Z",
               "fieldsType":"FieldsV1",
               "fieldsV1":{
                  "f:status":{
                     "f:addresses":{
                        "k:{\"type\":\"InternalIP\"}":{
                           "f:address":{
                              
                           }
                        }
                     },
                     "f:allocatable":{
                        "f:memory":{
                           
                        }
                     },
                     "f:capacity":{
                        "f:memory":{
                           
                        }
                     },
                     "f:conditions":{
                        "k:{\"type\":\"DiskPressure\"}":{
                           "f:lastHeartbeatTime":{
                              
                           }
                        },
                        "k:{\"type\":\"MemoryPressure\"}":{
                           "f:lastHeartbeatTime":{
                              
                           }
                        },
                        "k:{\"type\":\"PIDPressure\"}":{
                           "f:lastHeartbeatTime":{
                              
                           }
                        },
                        "k:{\"type\":\"Ready\"}":{
                           "f:lastHeartbeatTime":{
                              
                           },
                           "f:lastTransitionTime":{
                              
                           },
                           "f:message":{
                              
                           },
                           "f:reason":{
                              
                           },
                           "f:status":{
                              
                           }
                        }
                     },
                     "f:images":{
                        
                     },
                     "f:nodeInfo":{
                        "f:bootID":{
                           
                        },
                        "f:machineID":{
                           
                        },
                        "f:systemUUID":{
                           
                        }
                     }
                  }
               },
               "subresource":"status"
            }
         ]
      },
      "spec":{
         "podCIDR":"10.244.0.0/24",
         "podCIDRs":[
            "10.244.0.0/24"
         ],
         "providerID":"kind://docker/kind/kind-control-plane"
      },
      "status":{
         "capacity":{
            "cpu":"5",
            "ephemeral-storage":"107077304Ki",
            "hugepages-1Gi":"0",
            "hugepages-2Mi":"0",
            "hugepages-32Mi":"0",
            "hugepages-64Ki":"0",
            "memory":"10958488Ki",
            "pods":"110"
         },
         "allocatable":{
            "cpu":"5",
            "ephemeral-storage":"107077304Ki",
            "hugepages-1Gi":"0",
            "hugepages-2Mi":"0",
            "hugepages-32Mi":"0",
            "hugepages-64Ki":"0",
            "memory":"10958488Ki",
            "pods":"110"
         },
         "conditions":[
            {
               "type":"MemoryPressure",
               "status":"False",
               "lastHeartbeatTime":"2023-12-07T11:50:27Z",
               "lastTransitionTime":"2023-12-06T14:21:08Z",
               "reason":"KubeletHasSufficientMemory",
               "message":"kubelet has sufficient memory available"
            },
            {
               "type":"DiskPressure",
               "status":"False",
               "lastHeartbeatTime":"2023-12-07T11:50:27Z",
               "lastTransitionTime":"2023-12-06T14:21:08Z",
               "reason":"KubeletHasNoDiskPressure",
               "message":"kubelet has no disk pressure"
            },
            {
               "type":"PIDPressure",
               "status":"False",
               "lastHeartbeatTime":"2023-12-07T11:50:27Z",
               "lastTransitionTime":"2023-12-06T14:21:08Z",
               "reason":"KubeletHasSufficientPID",
               "message":"kubelet has sufficient PID available"
            },
            {
               "type":"Ready",
               "status":"True",
               "lastHeartbeatTime":"2023-12-07T11:50:27Z",
               "lastTransitionTime":"2023-12-06T14:21:28Z",
               "reason":"KubeletReady",
               "message":"kubelet is posting ready status"
            }
         ],
         "addresses":[
            {
               "type":"InternalIP",
               "address":"172.19.0.2"
            },
            {
               "type":"Hostname",
               "address":"kind-control-plane"
            }
         ],
         "daemonEndpoints":{
            "kubeletEndpoint":{
               "Port":10250
            }
         },
         "nodeInfo":{
            "machineID":"3489e0d51f694e4385ee5dedac53736c",
            "systemUUID":"3489e0d51f694e4385ee5dedac53736c",
            "bootID":"a28a8c69-2fc4-4bda-afe3-54644dd3a089",
            "kernelVersion":"5.10.104-linuxkit",
            "osImage":"Debian GNU/Linux 11 (bullseye)",
            "containerRuntimeVersion":"containerd://1.7.1",
            "kubeletVersion":"v1.27.3",
            "kubeProxyVersion":"v1.27.3",
            "operatingSystem":"linux",
            "architecture":"arm64"
         },
         "images":[
            {
               "names":[
                  "docker.elastic.co/beats/metricbeat@sha256:9972dd91739655e20e49a0edb4e26811dca75f0740318a29ba26fc086d3d78af",
                  "docker.elastic.co/beats/metricbeat:8.12.0-SNAPSHOT"
               ],
               "sizeBytes":149012603
            },
            {
               "names":[
                  "docker.elastic.co/beats/filebeat@sha256:9c2e3c7b8c1a03fcdb2021734898e8ad33aefb77d2542b373bc3ba5e154d8be2",
                  "docker.elastic.co/beats/filebeat:8.12.0-SNAPSHOT"
               ],
               "sizeBytes":141949252
            },
            {
               "names":[
                  "docker.elastic.co/beats/metricbeat@sha256:40f8a6b2b6dfad26295112b144c83cfbe793ae667d7cce687d12b8d898b92937",
                  "docker.elastic.co/beats/metricbeat:8.0.0-SNAPSHOT"
               ],
               "sizeBytes":103670593
            },
            {
               "names":[
                  "docker.elastic.co/beats/filebeat@sha256:9b3cec4fcbb3a1a8b6d72efcd6ebaa68eb17a942c8be48b20a7c6a11f1f3a6dc",
                  "docker.elastic.co/beats/filebeat:8.0.0-SNAPSHOT"
               ],
               "sizeBytes":95587869
            },
            {
               "names":[
                  "registry.k8s.io/etcd:3.5.7-0"
               ],
               "sizeBytes":80665728
            },
            {
               "names":[
                  "docker.io/library/import-2023-06-15@sha256:024134bb4e61a4975c5c15db76a7e3571eea74eff90c12a730781bf9c9daedd0",
                  "registry.k8s.io/kube-apiserver:v1.27.3"
               ],
               "sizeBytes":79827455
            },
            {
               "names":[
                  "docker.io/library/import-2023-06-15@sha256:336af6020e6377f586577425f1314d95067a9b4a1c8707e90d5062823ec03f43",
                  "registry.k8s.io/kube-controller-manager:v1.27.3"
               ],
               "sizeBytes":71504013
            },
            {
               "names":[
                  "docker.io/library/import-2023-06-15@sha256:67c927df0c79fb7415d0fc925570687fbec9a36cf13145a6430f9da059965dad",
                  "registry.k8s.io/kube-proxy:v1.27.3"
               ],
               "sizeBytes":68097533
            },
            {
               "names":[
                  "docker.io/library/import-2023-06-15@sha256:4b3d947dd06f4f5e4f417ec4da4bc83017f7cb5387d053ea2b6b906825011b7c",
                  "registry.k8s.io/kube-scheduler:v1.27.3"
               ],
               "sizeBytes":57610381
            },
            {
               "names":[
                  "docker.io/kindest/kindnetd:v20230511-dc714da8"
               ],
               "sizeBytes":25334607
            },
            {
               "names":[
                  "docker.io/kindest/local-path-provisioner:v20230511-dc714da8"
               ],
               "sizeBytes":17275248
            },
            {
               "names":[
                  "registry.k8s.io/coredns/coredns:v1.10.1"
               ],
               "sizeBytes":14557471
            },
            {
               "names":[
                  "registry.k8s.io/kube-state-metrics/kube-state-metrics@sha256:a15ca437f2309b769caa36a88240ce0266d67028f02da90f1c817c849b144273",
                  "registry.k8s.io/kube-state-metrics/kube-state-metrics:v2.7.0"
               ],
               "sizeBytes":11371848
            },
            {
               "names":[
                  "docker.io/kindest/local-path-helper:v20230510-486859a6"
               ],
               "sizeBytes":2922287
            },
            {
               "names":[
                  "registry.k8s.io/pause:3.7"
               ],
               "sizeBytes":268400
            }
         ]
      }
   }
}